include: package:very_good_analysis/analysis_options.3.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    use_super_parameters : false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/injector.config.dart
  errors:
    invalid_annotation_target: ignore
