name: test_lime_commerce
description: Test Lime Commerce Flutter App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  dartz: ^0.10.1
  dio: ^4.0.6
  floor: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  shimmer: ^2.0.0
  sqflite: ^2.0.2+1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  floor_generator: ^1.2.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  retrofit_generator: ">=3.0.0 <4.0.0"
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
