name: test_lime_commerce
description: Test Lime Commerce Flutter App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.7.0
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.7.0
  floor: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  freezed_annotation: ^2.2.0
  get_it: ^8.0.2
  injectable: ^2.1.0
  intl: ^0.19.0
  json_annotation: ^4.7.0
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^4.4.1
  shimmer: ^3.0.0
  sqflite: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  floor_generator: ^1.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.5.4
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.5
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
